Adaptive Homes page with routing and google map
selim13/airbnb-demo-frontend pull request #3
Opened 2017-11-16 08:56 UTC by selim13

https://build-qxzsxflsbp.now.sh/

2017-11-16 20:01 UTC, evgenyrodionov commented
Фильтры не как в макете

![image](https://user-images.githubusercontent.com/775692/32913005-098851d2-cb22-11e7-8422-46044716113d.png)

2017-11-16 20:04 UTC, imevro requested changes

2017-11-16 20:04 UTC, evgenyrodionov commented on package.json
> +    "serve": "^6.4.1",
а зачем?

2017-11-16 20:04 UTC, evgenyrodionov commented on package.json
> +    "now-start": "serve -s ./build"
нау и так это делает

2017-11-16 20:04 UTC, evgenyrodionov commented on package.json
> +    "now-start": "serve -s ./build"
но за попытку респект

2017-11-16 20:04 UTC, evgenyrodionov commented on src/App.js
> +import Front from "./Front";
Main либо Landing обычно называют

2017-11-16 20:04 UTC, evgenyrodionov commented on src/Experiences/staticData.js
> +    reviews: { rating: 4, number: 44 }
count

2017-11-16 20:04 UTC, evgenyrodionov commented on src/Homes/List.js
> +      <Map>
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Map

2017-11-18 08:57 UTC, selim13 commented
https://build-xgdnxxryzn.now.sh

2017-11-18 12:20 UTC, evgenyrodionov commented
Цвет слишком чёрный у шрифтов
в хедере бордер не тот

![image](https://user-images.githubusercontent.com/775692/32980236-c9a7bfc8-cc73-11e7-90fe-2f8946bd9375.png)

опять же цвет бордеров
![image](https://user-images.githubusercontent.com/775692/32980245-df34b4f4-cc73-11e7-8437-29c0b7042cfd.png)

Бордеры у фильтра
![image](https://user-images.githubusercontent.com/775692/32980253-06507b68-cc74-11e7-866d-d309ba01436c.png)

2017-11-18 12:25 UTC, imevro requested changes

2017-11-18 12:25 UTC, evgenyrodionov commented on src/Homes/Filters/Dates.js
> +    let dateText = "Dates";
нахуй мутабельность!

2017-11-18 12:25 UTC, evgenyrodionov commented on src/Homes/Filters/Dates.js
> +    let dateText = "Dates";
вынеси в отдельную функцию dateLabelFormatter, туда передавай аргументы и делай разные return

2017-11-18 12:25 UTC, evgenyrodionov commented on src/Homes/Filters/index.js
> +            <DesktopFilterButton>
бля как-то сложновато тут выглядит всё

2017-11-18 14:38 UTC, selim13 commented
https://build-ulxymbmbli.now.sh/

Дефолтный текста я брал из макета: #383838;
даже в html {} его указал

2017-11-19 09:09 UTC, imevro approved these changes

2017-11-19 09:09 UTC, merged

2017-11-19 09:10 UTC, evgenyrodionov commented
Гит пулл в мастере, новый бранч от него будешь делать