Filters logic
selim13/airbnb-demo-frontend pull request #5
Opened 2017-11-24 19:39 UTC by selim13

неуспел доделать price

2017-11-24 23:30 UTC, evgenyrodionov commented
Поч с плюсами?
![image](https://user-images.githubusercontent.com/775692/33225440-868c0400-d188-11e7-9195-cba3251d0152.png)

Чё-то всё криво
![image](https://user-images.githubusercontent.com/775692/33225442-9186cc6e-d188-11e7-80ce-7af977e3088e.png)

2017-11-24 23:31 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/33225446-af8673b8-d188-11e7-949d-4da11b1c2b29.png)

2017-11-24 23:34 UTC, imevro requested changes

2017-11-24 23:34 UTC, evgenyrodionov commented on package.json
> +    "lodash.includes": "^4.3.0",
используй основной лоудеш

2017-11-25 08:56 UTC, selim13 commented
https://build-unfsdbfmod.now.sh

2017-11-25 14:25 UTC, evgenyrodionov commented
Сделай cursor pointer при ховере
![image](https://user-images.githubusercontent.com/775692/33231373-908a7de2-d205-11e7-8316-b62e2b8ded9f.png)

В more filters счетчик странный — туда почему-то показывает выбранные значения в остальных)
![image](https://user-images.githubusercontent.com/775692/33231378-a60df4be-d205-11e7-8749-6fc8bfd8d625.png)

2017-11-25 14:27 UTC, imevro requested changes

2017-11-25 14:27 UTC, evgenyrodionov commented on src/Homes/Filters/Price/index.js
> +            onFilterChange({ min: values.values[0], max: values.values[1] })
values.values? забавно

2017-11-25 17:01 UTC, selim13 commented
https://build-mgbeadwnze.now.sh

2017-11-26 15:45 UTC, imevro approved these changes

2017-11-26 15:46 UTC, evgenyrodionov commented
Странно что adults и чилдрен объединяются, а пиздюки идут отдельно
![image](https://user-images.githubusercontent.com/775692/33241692-22379084-d2da-11e7-9291-778d0da9506f.png)

2017-11-26 15:47 UTC, evgenyrodionov commented
А так всё ок

2017-11-26 15:47 UTC, merged

2017-11-26 15:48 UTC, evgenyrodionov commented
Сделаешь гит пулл в мастере, новые бранчи — от него