Adaptive rooms page (without modal)
selim13/airbnb-demo-frontend pull request #6
Opened 2017-11-24 19:43 UTC by selim13

2017-11-24 23:35 UTC, evgenyrodionov commented
Тоже фиксед
![image](https://user-images.githubusercontent.com/775692/33225473-50f6d8f0-d189-11e7-9660-e86c6e092851.png)

2017-11-24 23:40 UTC, imevro requested changes

2017-11-24 23:40 UTC, evgenyrodionov commented on src/Homes/Show/Amenities/index.js
> +        </Col>
нет нужды оборачивать в строчки, просто каждый элемент оберни в колонку

2017-11-24 23:40 UTC, evgenyrodionov commented on src/Homes/Show/RequestForm.js
> +  -: #383838;
лол

2017-11-24 23:40 UTC, evgenyrodionov commented on src/Homes/Show/RequestForm.js
> +    <Form {...props}>
лучше расписывай те параметры которые ты даешь — явное лучше неявного

2017-11-25 17:01 UTC, selim13 commented
https://build-mgbeadwnze.now.sh

2017-11-28 08:54 UTC, selim13 commented
https://build-lnlraudbxn.now.sh

2017-11-28 22:27 UTC, evgenyrodionov commented
Проверю утром

2017-11-29 08:53 UTC, selim13 commented
https://build-rrlundvuzd.now.sh

2017-11-29 16:53 UTC, evgenyrodionov commented
Календарь не открывается, селект не работает
![image](https://user-images.githubusercontent.com/775692/33387663-e96deb6a-d53e-11e7-880e-af18f5b9af00.png)
![image](https://user-images.githubusercontent.com/775692/33387688-fc7a7ba6-d53e-11e7-99d1-c2612f7ec01f.png)

2017-11-29 16:59 UTC, imevro approved these changes

2017-12-01 08:58 UTC, selim13 commented
https://build-tpvurdmpli.now.sh 
Формочка в rooms

2017-12-01 16:57 UTC, imevro requested changes

2017-12-01 16:57 UTC, evgenyrodionov commented on src/Homes/Show/RequestForm/DateDropdown.js
> +              this.props.dates.endDate
ну вынеси в константу

2017-12-01 16:57 UTC, evgenyrodionov commented on src/Homes/Show/RequestForm/GuestsDropdown.js
> +function guestsLabelFormatter(adults, children, infants) {
почему бы не переиспользовать существующий?

2017-12-02 08:54 UTC, selim13 commented
https://build-iotbvncpml.now.sh

2017-12-02 16:01 UTC, imevro approved these changes

2017-12-02 20:50 UTC, selim13 commented
https://build-efluovylmx.now.sh

2017-12-07 22:20 UTC, imevro approved these changes

2018-01-29 10:41 UTC, merged